### ISSUE TITLE
Speed up note importing

### ISSUE THREAD

**Issue by samhstn** [ankiviewer/ankiviewer#14]
The current method is:
+ run one sqlite join query which will generate a large list
+ pass this list into an elixir function which will iterate through this list inserting each note

Better would be:
+ dump the sqlite db into some postgres tables
+ run a command through these tables to format them
+ copy these over to our notes table (again using vanilla sql)
(following something like this: https://stackoverflow.com/questions/4581727/convert-sqlite-sql-dump-file-to-postgresql/4581921#4581921)

**Comment by shouston3** [comment]
#23 may be sufficient
